### PR TITLE
Revert "Updated README to include virtualenv option."

### PR DESCRIPTION
**Pull request by vladdoster**
Reverts patdaburu/cookiecutter-click#33

I missed the parentheses when you added to the READme. Is that a cookiecutter option to select both, but I think it should be removed?

### CODE REVIEW

**Comment by vladdoster** [comment]
If you meant to have the parentheses, c lose this PR.

**Comment by patdaburu** [comment]
Good catch.  I didn't notice it before, but now that I'm looking at it, it seems to be there for the license in the README also:

```
Select license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1,2 (1, 2, 3, 4, 5) [1]: 1
```

Running it again (cookiecutter 1.6.0) it seems to appear for every option...

```
project_name [ClickCLI]: 
package_name [clickcli]: 
cli_name [clickcli]: 
project_version [0.0.1]: 
project_description [This is my click command-line app project.]: 
Select python_version:
1 - 3.6
2 - 3.7
3 - 3.8
Choose from 1, 2, 3 (1, 2, 3) [1]: 
Select virtualenv:
1 - virtualenv
2 - python3
Choose from 1, 2 (1, 2) [1]: 
Select sphinx_theme:
1 - alabaster
2 - readthedocs
Choose from 1, 2 (1, 2) [1]: 
```

**Comment by patdaburu** [comment]
I'll look into it some more and see if I can figure out why it appears this way.  (Maybe it's a new  cookiecutter option?)

**Comment by patdaburu** [comment]
I think the changes made in https://github.com/patdaburu/cookiecutter-click/pull/37#event-2689411013 supersede this revert so I will go ahead and close it.

**Pull request closed without merging**
